
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PruebaCascada.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Subcategorias
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Subcategorias()
    {

        this.Productos = new HashSet<Productos>();

    }


    public int id { get; set; }

    public string nombre { get; set; }

    public int idcat { get; set; }



    public virtual Categorias Categorias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Productos> Productos { get; set; }

}

}
